name: 部署文档

on:
  push:
    branches:
      - docs # 确保这是你正在使用的分支名称

permissions:
  contents: write

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8


      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm


      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # 这是文档部署到的分支名称
          folder: docs/.vuepress/dist

  move-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch file from docs branch
        run: |
          # 假设要移动的文件是 docs/sample.txt，你需要替换成实际文件名
          git fetch origin docs:docs
          git checkout docs -- ./README.md

    #   - name: Move file to target location
    #     run: |
    #       # 确保目标目录存在，你需要替换 target_folder 为实际目标目录
    #       mv ./README.md ./

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./README.md
          git commit -m "move README.md"
          git push
